---

- name: restart systemd-sysctl
  service:
    state: restarted
    name: systemd-sysctl

- name: restart rke2-server
  service:
    state: restarted
    name: rke2-server

- name: restart rke2-agent
  service:
    state: restarted
    name: rke2-agent
